"""
status_md.py — Markdown STATUS.md writer derived from ProjectReport.

Writes .ai/STATUS.md from the report model, preserving any legacy snapshot section.
"""

from __future__ import annotations

from pathlib import Path

from .model import ProjectReport


def write_status_md(report: ProjectReport, ai_dir: Path):
    """Write STATUS.md from the report model."""
    lines = ["# Project Status", ""]
    lines.append("> Auto-generated by `ai status`. Do not edit manually.")
    lines.append("")
    lines.append(f"## Phase\n{report.current_phase}")
    lines.append("")
    lines.append(f"## Progress\n[{'#' * (report.overall_progress // 5)}{'.' * (20 - report.overall_progress // 5)}] "
                 f"{report.overall_progress}%  "
                 f"({report.task_counts.get('done', 0)}/{len(report.tasks)} tasks done)")
    lines.append("")

    # Summary
    lines.append("## Summary")
    for s in report.summary:
        lines.append(f"- {s}")
    lines.append("")

    # Task counts
    lines.append("## Task Counts")
    lines.append("| Status | Count |")
    lines.append("|--------|-------|")
    for col in report.columns:
        lines.append(f"| {col.replace('_', ' ').title()} | {report.task_counts.get(col, 0)} |")
    lines.append("")

    # Tasks by status (non-done)
    for col in report.columns:
        if col == "done":
            continue
        col_tasks = [t for t in report.tasks if t.status == col]
        if not col_tasks:
            continue
        lines.append(f"## {col.replace('_', ' ').title()} ({len(col_tasks)})")
        for t in col_tasks:
            owner = t.owner or t.owner_role or "Unassigned"
            pri = f" `{t.priority}`" if t.priority else ""
            lines.append(f"- **{t.id}**: {t.title}{pri} (owner: {owner})")
        lines.append("")

    # Done
    done_tasks = [t for t in report.tasks if t.status == "done"]
    if done_tasks:
        lines.append(f"## Completed ({len(done_tasks)})")
        for t in done_tasks:
            lines.append(f"- ~~{t.id}~~: {t.title}")
        lines.append("")

    # Milestones
    if report.milestones:
        lines.append("## Milestones")
        for m in report.milestones:
            marker = "[x]" if m.status == "done" else "[ ]"
            lines.append(f"- {marker} **{m.id}**: {m.title}")
        lines.append("")

    # Blockers
    lines.append("## Blockers")
    if report.blockers:
        for b in report.blockers:
            lines.append(f"- {b}")
    else:
        lines.append("None")
    lines.append("")

    # Approvals
    lines.append("## Pending Approvals")
    if report.approvals_pending:
        for a in report.approvals_pending:
            lines.append(f"- {a.trigger_id}: {a.description}")
    else:
        lines.append("None")
    lines.append("")

    # Decisions
    lines.append("## Recent Decisions")
    if report.decisions_recent:
        for d in report.decisions_recent:
            lines.append(f"- [{d.date}] {d.title}")
    else:
        lines.append("See DECISIONS.md")
    lines.append("")

    # Next actions
    if report.next_actions:
        lines.append("## Next Actions")
        for i, a in enumerate(report.next_actions, 1):
            lines.append(f"{i}. {a}")
        lines.append("")

    lines.append(f"---\n*Last updated: {report.generated_at}*")

    # Preserve legacy snapshot
    status_path = ai_dir / "STATUS.md"
    legacy_section = ""
    if status_path.exists():
        existing = status_path.read_text()
        marker = "## Legacy Status Snapshot"
        idx = existing.find(marker)
        if idx >= 0:
            legacy_section = "\n\n" + existing[idx:]

    status_path.write_text("\n".join(lines) + legacy_section + "\n")
